### ISSUE TITLE
#数据咨询

### ISSUE THREAD

**Issue by qianbabe** [lq-sjtu/pattern-recognition#1]
hello!很抱歉打扰您，我想请问一下这整个代码用到的原始数据是什么呢？本人新手刚刚接触字典学习，希望您能回复，谢谢！

**Comment by lqecho** [comment]
你好，原始数据是耶鲁大学的人脸公开数据集，38个人的人脸数据，每人64幅共计2432幅大小为192×168的图片。网上应该可以搜的到，查不到的话，明天发你百度网盘。这个项目的代码有些地方可能有问题，仅供参考。谢谢！
----- 原始邮件 -----
发件人: "qianbabe" ***@***.***>
收件人: "lq-sjtu/pattern-recognition" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期二, 2021年 7 月 06日 下午 9:35:52
主题: [lq-sjtu/pattern-recognition] #数据咨询 (#1)

hello!很抱歉打扰您，我想请问一下这整个代码用到的原始数据是什么呢？本人新手刚刚接触字典学习，希望您能回复，谢谢！

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/lq-sjtu/pattern-recognition/issues/1

**Comment by qianbabe** [comment]
> 你好，原始数据是耶鲁大学的人脸公开数据集，38个人的人脸数据，每人64幅共计2432幅大小为192×168的图片。网上应该可以搜的到，查不到的话，明天发你百度网盘。这个项目的代码有些地方可能有问题，仅供参考。谢谢！ ----- 原始邮件 ----- 发件人: "qianbabe" ***@***.***> 收件人: "lq-sjtu/pattern-recognition" ***@***.***> 抄送: "Subscribed" ***@***.***> 发送时间: 星期二, 2021年 7 月 06日 下午 9:35:52 主题: [lq-sjtu/pattern-recognition] #数据咨询 (#1) hello!很抱歉打扰您，我想请问一下这整个代码用到的原始数据是什么呢？本人新手刚刚接触字典学习，希望您能回复，谢谢！
> […](#)
> -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #1
谢谢！如果您方便的话，可以加我网盘好友发给我吗？我的用户名是hahajuice，再次感谢您分享的代码和数据！

**Comment by lqecho** [comment]
> > 你好，原始数据是耶鲁大学的人脸公开数据集，38个人的人脸数据，每人64幅共计2432幅大小为192×168的图片。网上应该可以搜的到，查不到的话，明天发你百度网盘。这个项目的代码有些地方可能有问题，仅供参考。谢谢！ ----- 原始邮件 ----- 发件人: "qianbabe" _**@**_._**> 收件人: "lq-sjtu/pattern-recognition" _**@**_.**_> 抄送: "Subscribed" _**@**_.***> 发送时间: 星期二, 2021年 7 月 06日 下午 9:35:52 主题: [lq-sjtu/pattern-recognition] #数据咨询 (#1) hello!很抱歉打扰您，我想请问一下这整个代码用到的原始数据是什么呢？本人新手刚刚接触字典学习，希望您能回复，谢谢！
> > […](#)
> > -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #1
> > 谢谢！如果您方便的话，可以加我网盘好友发给我吗？我的用户名是hahajuice，再次感谢您分享的代码和数据！

链接：https://pan.baidu.com/s/1jdAbBN4AhqHJcpPCiqaAcA 
提取码：rpnn
